### ISSUE TITLE
Carousel jittering and not looping

### ISSUE THREAD

**Issue by vuolen** [osakunta/website#36]
Maybe limit framerate on the opacity

**Comment by YB-BigSwan** [comment]
Upgraded embla carousel and that seems (?) to have addressed the jittering issue, however the looping thing is weird. Because it *does* do the infinite loop properly at first, but then after infinite looping to the first image it does the weird wraparound thing to the second image. There might be some mismatch in slide nubmers somewhere?

**Comment by vuolen** [comment]
Fixed by #42
